- name: install pyhon libraries 
  ansible.builtin.pip:  
    name: 
    - PyMySQL 
    - cryptography
    executable: pip3.9
- name: install mysql-server 
  ansible.builtin.package: 
    name: mysql-server 
    state: present 

- name: start mysql-server 
  ansible.builtin.service: 
    name: mysqld 
    state: started 
    enabled: yes 
- name: connect to mysql server if logins are present 
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ mysql_rootpass }}"
    login_host: "{{ mysql_hostlogin }}"
  ignore_errors: true 
  register: mysql_info

- name: print the mysql_info output 
  ansible.builtin.debug: 
    msg: "{{ mysql_info }}" 

- name: set up the root password for mysql-server 
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_rootpass }}"
  when: mysql_info.failed is true 

