# remove the existing code 
# create again
# download code 
# extract 
- name: remove existing app location
  ansible.builtin.file:
    name: app_location
    state: absent 
- name: create directory 
  ansible.builtin.file: 
    path: "{{ app_location }}"
    state: directory 
- name: "download the code and unarchieve {{ component }} code"
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip"
    dest: "{{ app_location }}"
    remote_src: yes  
